version: '3'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ~/environments/myapps-be/.env


  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx_proxy:v1
    depends_on:
      - nodejs
    ports:
      - 3001:3000
    