# version: '3'

services:
  nodejs:
    build: .
    env_file:
      - ~/environments/myapps-be/.env
    # ports:
    #   - "3000:3000"


  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx_proxy:v1
    depends_on:
      - nodejs
    ports:
      - 3000:3000
    